# =============================================================================
# config.ps1 - Loads setup-config.json and exposes variables to all scripts
# Dot-source this at the top of each script: . "$PSScriptRoot\config.ps1"
# To change any setting, edit setup-config.json — do not edit this file.
# =============================================================================

$configFile = "$PSScriptRoot\setup-config.json"
if (!(Test-Path $configFile)) {
    Write-Error "setup-config.json not found at: $configFile"
    exit 1
}
$cfg = Get-Content $configFile -Raw | ConvertFrom-Json

# --- Paths ---
$VMName         = $cfg.VMName
$VMBasePath     = $cfg.VMBasePath
$ISOPath        = $cfg.ISOPath
$TeraSourcePath = $cfg.TeraSourcePath
$BotSourcePath  = $cfg.BotSourcePath
$EasyGpuPvPath  = $cfg.EasyGpuPvPath

# --- VM Resources ---
$VMSwitchName   = $cfg.VMSwitchName
$VMRAM          = $cfg.VMRamGB * 1GB
$VMvCPUs        = $cfg.VMvCPUs
$VMOSDiskGB     = $cfg.VMOSDiskGB
$VMGameDiskGB   = $cfg.VMGameDiskGB

# --- VM Account ---
$VMUsername     = $cfg.VMUsername
$VMPassword     = $cfg.VMPassword
$VMCred         = New-Object System.Management.Automation.PSCredential(
                    $VMUsername,
                    (ConvertTo-SecureString $VMPassword -AsPlainText -Force)
                  )

# --- ZeroMQ ---
$ZMQPort        = $cfg.ZMQPort

# --- Derived paths (don't edit below) ---
$VMPath         = "$VMBasePath\$VMName"
$VMOSDisk       = "$VMPath\$VMName-os.vhdx"
$VMGameDisk     = "$VMPath\$VMName-game.vhdx"
